name: print_table
description: A simple library to generate text-based table for console-printing.
version: 1.0.1
homepage: https://ardeviot.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.8
